const AUDIT_EVENTS = {
  AUTH_LOGIN_SUCCESS: "AUTH_1001",
  AUTH_LOGIN_FAILED: "AUTH_1002",
  AUTH_LOGOUT: "AUTH_1003",
  AUTH_PASSWORD_RESET: "AUTH_1004",
  AUTH_REGISTRATION_FAILED: "AUTH_1005",
  AUTH_FORGOT_PASSWORD_SEND_LINK: "AUTH_1006",
  AUTH_REGISTRATION_SUCCESS: "AUTH_1007",
  AUTH_PASSWORD_CHANGE: "AUTH_1008",

  USER_EMAIL_VERIFY: "USER_2002",
  USER_ACCOUNT_DELETION: "USER_2003",
};

const AUDIT_REASONS = {
  AUTH: {
    EMAIL_NOT_FOUND: "ERR_AUTH_01",
    INVALID_PASSWORD: "ERR_AUTH_02",
    ACCOUNT_LOCKED: "ERR_AUTH_03",
    MFA_REQUIRED: "ERR_AUTH_04",
    TOKEN_EXPIRED: "ERR_AUTH_05",
    EMAIL_NOT_VERIFIED: "ERR_AUTH_06",
    USER_NOT_FOUND: "ERR_AUTH_07",
    EMAIL_CONFLICT: "ERR_AUTH_08",
  },
  SYSTEM: {
    RATE_LIMIT_EXCEEDED: "ERR_SYS_01",
    DATABASE_TIMEOUT: "ERR_SYS_02",
  },
};

export default { AUDIT_EVENTS, AUDIT_REASONS };
